### ISSUE TITLE
Load master room availability and floor options in parallel on the client

### ISSUE THREAD

**Issue by trioletas** [ctco-dev/bookie-client#3]
Current implementation executes the master room availability and floor options lookup on the server and renders the page only when both are resolved.
We can improve our UX and Time-To-Interactive metric by instead querying room availability and floor options concurrently on the client in two separate GraphQL queries:

ask for floorMasterRoom -> render the master room status as soon as it arrives
at the same time
ask for roomsOnMasterFloor  and show the progress bar in the meantime

This can be achieved by splitting the current query in two and by extracting available rooms on master floor to a separate component.

**Comment by trioletas** [comment]
Broken by 9c9aa54

**Comment by jelisejev** [comment]
Reverted 9c9aa54.
